---
title: "HW3-plotting"
author: "Sam Muir"
date: 2024-03-02
format:
  html:
    embed-resources: true
---

# Part 2a.

```{r, libraries, message=FALSE}
# libraries
library(tidyverse)
library(janitor)
library(sf)
library(sysfonts)
library(scales)
library(patchwork)
```

```{r}
animals <- read_csv("data/animals/PLT-GCEM-1610_Animals_9_0.CSV", skip = 2)[-c(1,2),]
biomass <- read_csv("data/biomass/PLT-GCEM-1610_Biomass_10_0.CSV", skip = 2)[-c(1,2),]
vegetation <- read_csv("data/vegetation/PLT-GCEM-1610_Vegetation_9_0.CSV", skip = 2)[-c(1,2),]
stemheight <- read_csv("data/stemheight/PLT-GCEM-1610_StemHeight_10_0.CSV", skip = 2)[-c(1,2),]
```

```{r, data cleaning, warning=FALSE, message=FALSE}
# data cleaning 

animals_clean <- animals %>%
  clean_names() %>%
  mutate_at(c("latitude", "longitude", "littoraria_count"), as.numeric) %>% # change cols to numeric
  mutate_at(c("grasshopper_abundance_index", "prokelisia_abundance_index", "littoraria_quadrat_area", "plot_number", "spartina_zone"), as.factor) %>% # change cols to factor
  mutate(date = lubridate::as_date(date)) # change date to a date

biomass_clean <- biomass %>%
  clean_names() %>%
  mutate_at(c("biomass_aboveground_green", "biomass_aboveground_brown", "biomass_aboveground_total", "biomass_belowground_0to10cm", "biomass_belowground_10to30cm", "biomass_belowground_total", "rhizomes_0to10cm", "root_to_shoot_ratio"), as.numeric) %>% # change cols to numeric
  mutate_at(c("spartina_zone", "replicate"), as.factor) %>% # change cols to factor
  mutate(date = lubridate::as_date(date)) # change date to a date

stemheight_clean <- stemheight %>%
  clean_names() %>%
  mutate_at(c("spartina_zone"), as.factor) %>% # change cols to factor
  mutate_at(c("core_number", "stem_number", "stem_height"), as.numeric) %>% # change cols to numeric
  mutate(date = lubridate::as_date(date))

## maybe there was a better way to do all of this? but seems like good practice either way 

# joining some of the data frames
stem_animals <- full_join(animals_clean, stemheight_clean, relationship = "many-to-many") %>% # join animals and stemheight
  mutate(year = as.factor(year(date)), # get year from the date
         month = as.factor(month(date))) %>% # get month from the date
  full_join(biomass_clean)
```

```{r}
# line plot for counts over the years
snail_plotting <- stem_animals %>%
  filter(year != 2013) %>%
  mutate(year_month = format(date, "%y/%m")) %>%
  group_by(year_month) %>%
  summarise(counts = sum(littoraria_count, na.rm = TRUE)) %>%
  mutate(year_month = ym(year_month))

line_chart <- ggplot(snail_plotting, aes(x = year_month, y = counts, group = 1)) +
  geom_point(color = "darkgreen") +
  geom_line(color = "darkgreen") +
  theme_bw() +
  labs(x = "Year", y = "Marsh Periwinkle Snail Count") +
  theme_minimal(base_family = "fira condensed") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(margin = margin(r = 15)),
        axis.title.x = element_text(margin = margin(t = 15)),
        panel.grid.major.x = element_line(color = "grey50", linewidth = 0.25, linetype = "dotted"),
        panel.grid.major.y = element_line(color = "grey50", linetype = "dotted")
        )
```

```{r}
# bar chart for counts by spartina zone
bar_chart <- stem_animals %>%
  filter(year != 2013) %>%
  mutate(spartina_zone_name = case_when(spartina_zone == "S" ~ "Short",
                                        spartina_zone == "M" ~ "Medium",
                                        spartina_zone == "T" ~ "Tall"),
         spartina_zone = factor(spartina_zone_name, levels = c("Short", "Medium", "Tall"))) %>%
  select(month, year, date, littoraria_count, spartina_zone) %>%
  group_by(spartina_zone) %>%
  summarise(littoraria_count = sum(littoraria_count, na.rm = TRUE)) %>%
  ggplot(., aes(x = spartina_zone, y = littoraria_count)) +
  geom_col(fill = "#455D44", color = "black") +
  theme_bw() +
  labs(x = "Marsh Grass Height Zone",
       y = "Marsh Periwinkle Snail Count") +
  theme_minimal(base_family = "fira condensed") +
  theme(panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.y = element_text(margin = margin(r = 15)),
        axis.title.x = element_text(margin = margin(t = 15)),
        panel.grid.major.x = element_line(color = "grey50", linewidth = 0.25, linetype = "dotted"),
        panel.grid.major.y = element_line(color = "grey50", linetype = "dotted")
        )
```


```{r}
# # prepare snail data for heatmap
# snail_heatmap <- stem_animals %>%
#   filter(year != 2013) %>%
#   mutate(month_name = as.factor(month.name[month]),
#          month_name = factor(month_name, levels = month.name)) %>%
#   select(month, month_name, year, date, littoraria_count, spartina_zone) %>%
#   group_by(month_name, year) %>%
#   summarise(littoraria_count = sum(littoraria_count, na.rm = TRUE))
# 
# additional_data <- data.frame(
#   month_name = factor(c("June", "September", "October", "October", "November", "November"),
#                       levels = month.name),
#   year = factor(c(2019, 2017, 2018, 2019, 2016, 2021))
# )
# 
# full_snail_heatmap <- full_join(snail_heatmap, additional_data)

# prepare grasshopper data for heatmap
invert_binary <- stem_animals %>%
  filter(year != 2013) %>%
  mutate(month_name = as.factor(month.name[month]),
         month_name = factor(month_name, levels = month.name),
         grasshopper_abundance_index = as.character(grasshopper_abundance_index),
         prokelisia_abundance_index = as.character(prokelisia_abundance_index),
         grasshopper_abundance_index = as.numeric(grasshopper_abundance_index),
         prokelisia_abundance_index = as.numeric(prokelisia_abundance_index),
         day = day(date)) %>%
  select(month, month_name, year, date, grasshopper_abundance_index, prokelisia_abundance_index) %>%
  group_by(month_name, year) %>%
  summarise(grasshopper = max(grasshopper_abundance_index),
            planthopper = max(prokelisia_abundance_index),
            grasshopper = as.factor(grasshopper),
            planthopper = as.factor(planthopper))

additional_data2 <- data.frame(
  month_name = factor(c("February", "June", "September", "October", "October", "November", "November"),
                      levels = month.name), year = factor(c(2020, 2019, 2017, 2018, 2019, 2016, 2021))
)

full_heatmap_data <- full_join(invert_binary, additional_data2) %>%
  pivot_longer(cols = grasshopper:planthopper, names_to = "Animal",
               values_to = "Abundance")
```

```{r}
# ggplot(full_snail_heatmap) +
#   geom_tile(aes(x = month_name, y = year, fill = littoraria_count), color = "slategrey") +
#   scale_fill_gradient(low = "white", high = "purple4") +
#   ggnewscale::new_scale_color() +
#   geom_tile(data = subset(full_snail_heatmap, is.na(littoraria_count)),
#             aes(x = month_name, y = year, color = "slategrey"), fill = "grey", linewidth = 0) +
#   labs(title = "Marsh Periwinkle Snail Counts", 
#        subtitle = "at the Georgia Coastal Ecosystem LTER Flux Tower (2014-2022)",
#        x = "",
#        y = "Year",
#        fill = "Snail Counts",
#        color = "No Data") +
#   theme_minimal(base_family = "fira condensed") +
#   theme(axis.line = element_blank(),
#         panel.grid = element_blank(),
#         panel.border = element_blank(),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 13),
#         axis.text.y = element_text(size = 13),
#         axis.title.y = element_text(margin = margin(r = 16), size = 17),
#         plot.title = element_text(size = 26, hjust = 0.5),  # Center the title
#         plot.subtitle = element_text(hjust = 0.5)) +
#   guides(color = guide_legend(override.aes = list(fill = "grey"), label = FALSE))
```

```{r}
# grasshopper_plot <- ggplot(grasshopper_heatmap) +
#   geom_tile(aes(x = month_name, y = year, fill = max_grasshopper), color = "black") +
#   scale_fill_manual(values = c("#DFE3CE","#BDCFA1","#455D44", "#23341E"), labels = c("Rare", "Common", "Abundant", "Very Abundant")) +
#   labs(title = "Invertebrate Animal Abundance at the\n Georgia Coastal Ecosystem LTER Flux Tower (2014-2022)", 
#        subtitle = "Grasshopper",
#        x = "",
#        y = "Year",
#        fill = "Abundance") +
#   theme_minimal(base_family = "fira condensed") +
#   theme(axis.line = element_blank(),
#         panel.grid = element_blank(),
#         panel.border = element_blank(),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 13),
#         axis.text.y = element_text(size = 13),
#         axis.title.y = element_text(margin = margin(r = 16), size = 17),
#         plot.title = element_text(size = 20, hjust = 0.5),  # Center the title
#         plot.subtitle = element_text(hjust = 0.5, size = 17)) +
#   guides(color = guide_legend(override.aes = list(fill = "grey"), label = FALSE))
```

```{r}
# planthopper_plot <- ggplot(planthopper_heatmap) +
#   geom_tile(aes(x = month_name, y = year, fill = max_planthopper), color = "black") +
#   scale_fill_manual(values = c(0 = "white", 1 = "#DFE3CE", 2 = "#BDCFA1", 3 = "#455D44", 4 = "#23341E"), 
#                     labels = c("Absent","Rare", "Common", "Abundant", "Very Abundant")) +
#   labs(subtitle = "Planthopper", 
#        x = "",
#        y = "Year",
#        fill = "Abundance") +
#   theme_minimal(base_family = "fira condensed") +
#   theme(axis.line = element_blank(),
#         panel.grid = element_blank(),
#         panel.border = element_blank(),
#         axis.text.x = element_text(angle = 45, hjust = 1, size = 13),
#         axis.text.y = element_text(size = 13),
#         axis.title.y = element_text(margin = margin(r = 16), size = 17),
#         plot.title = element_text(size = 17, hjust = 0.5),  # Center the title
#         plot.subtitle = element_text(hjust = 0.5, size = 17)) +
#   guides(color = guide_legend(override.aes = list(fill = "grey"), label = FALSE))
```

```{r}
ggplot(full_heatmap_data) +
  geom_tile(aes(x = month_name, y = year, fill = Abundance), color = "black") +
  scale_fill_manual(values = c("white","#DFE3CE","#BDCFA1","#455D44", "#23341E"), 
                    labels = c("Absent","Rare", "Common", "Abundant", "Very Abundant"),
                    na.value = "grey") +
  facet_wrap(~Animal) +
  labs(title = "Invertebrate Animal Abundance at the\n Georgia Coastal Ecosystem LTER Flux Tower (2014-2022)", 
       x = "",
       y = "Year",
       fill = "Abundance") +
  theme_minimal(base_family = "fira condensed") +
  theme(axis.line = element_blank(),
        panel.grid = element_blank(),
        panel.border = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1, size = 13),
        axis.text.y = element_text(size = 13),
        axis.title.y = element_text(margin = margin(r = 16), size = 17),
        plot.title = element_text(size = 20, hjust = 0.5),  # Center the title
        plot.subtitle = element_text(hjust = 0.5, size = 17),
        strip.text = element_text(size = 13)) 
```
